name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
        
    - name: Setup RabbitMQ with username and password
      uses: mer-team/rabbitmq-mng-action@v1.2
      with:
        RABBITMQ_PORT: 5672
        RABBITMQ_USER: rabbit
        RABBITMQ_PASS: rabbitr

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - name: Test
      run: go test -v ./...
