name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    services:
      rabbitmq:
        image: rabbitmq:alpine
        env:
          RABBITMQ_DEFAULT_USER: rabbit
          RABBITMQ_DEFAULT_PASS: rabbit
        ports:
          - 5672:5672
          - 15672:15672
          - 15671:15671

    steps:
    - uses: actions/checkout@v2

    - name: Waiting for RabbitMQ    
      uses: iFaxity/wait-on-action@v1
      with:
        resource: tcp://localhost:5672

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - name: Test
      run: go test -v ./...
