name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Start RabbitMQ
      uses: mer-team/rabbitmq-mng-action@v1.2
      with:
        RABBITMQ_PORT: 5672
        RABBITMQ_USER: rabbit
        RABBITMQ_PASS: rabbit

    - name: Waiting for RabbitMQ    
      uses: iFaxity/wait-on-action@v1
      with:
        resource: tcp://localhost:5672

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - name: Test
      run: go test -v ./...
