name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Start RabbitMQ
      uses: getong/rabbitmq-action@v1.2
      with:
        rabbitmq user: 'rabbit'
        rabbitmq password: 'rabbit'
        rabbitmq vhost: '/'

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - name: Test
      run: go test -v ./...
